# Imagem base Python
FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia e instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código e XSD
COPY . .

# Expõe porta (Railway define dinamicamente)
EXPOSE 8080

# Comando para rodar
CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT}"]
